version: '3.8'

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7257:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=MadnixDB;User Id=sa;Password=11111111;TrustServerCertificate=True;
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7060:7060"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=MadnixDB;User Id=sa;Password=11111111;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "11111111"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: